import type { PrismaClient } from '@prisma/client';
import type { AuthUser } from './middleware/auth.js';

// `Env` is the global ambient binding type generated by `wrangler types`
// (see worker-configuration.d.ts) from server/wrangler.toml — rerun that
// command after changing wrangler.toml so this stays in sync.
export type Bindings = Env;

export interface Variables {
  prisma: PrismaClient;
  user: AuthUser;
}

export type AppEnv = { Bindings: Bindings; Variables: Variables };
